[build.environment]
  NODE_VERSION = "16.15.0"
  NPM_FLAGS = "--version"

[build]
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"
  publish = "build/"
  functions = "functions/"

[dev]
 command = "pnpm run dev"
 targetPort = 5173
 port = 8888
 
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
