<script>
	import Icon from '$lib/components/Icon.svelte';
	import Modal from '$lib/components/base/Modal.svelte';
</script>

<Modal id="dnd-dice-character-info-modal" class="bg-white text-base-900">
	<div slot="title">
		<Icon name="info" /> &nbsp; Info
	</div>

	<ul class="mx-4 list-disc">
		<li>Each stat is generated by rolling 4 d6 and taking the 3 highest rolls.</li>
		<li>
			The number immediately below the dice is the sum of the 3 highest rolls. The number below that
			is its corresponding stat. You can find the table by clicking the "Modifiers" button
		</li>
		<li>
			There are 6 stats: strength, dexterity, constitution, intelligence, wisdom, and charisma.
		</li>
		<li>Use the dropdown menu to choose which stat you want to assign to which roll.</li>
		<li>
			D&amp;D Character Roller is great for a DM who wants to quickly create new NPCs and download
			their stats for later, for new players, or to start a quick campaign!
		</li>
		<li>
			You can use the tab key to navitage inputs. Use arrow keys to choose your stat, or enter to
			open the dropdown.
		</li>
	</ul>
</Modal>
